### ISSUE TITLE
Double Click, Click & Hold

### ISSUE THREAD

**Issue by nccchirag** [makermoekoe/Picoclick#1]
Can you also provide a sample with the below functionality included?

1. Click
2. Double Click
3. Long Press -- Click & Hold

For double click/click&hold, with the latching logic will I have to power on picoclick with a single click first and then double click to operate? 
Can you elaborate on this please?

**Comment by makermoekoe** [comment]
I will add examples for all this later.
To answer your second question: No, the first (power on click) can be read out as normal. So for a double press you only have to press the button twice.

**Comment by makermoekoe** [comment]
Hey, I just came across this issue thread and I wanna mention that there is a fully testet button counter sketch with and without MQTT in the repo. It can count button presses and button holds. (It is the last button press which can be hold)

The sketch answers with a green blinking animation if it just counts single presses and with a red animation if the last button press was held. All this is based on interrupts, so it is possible during the WLAN connect period.
