### ISSUE TITLE
WiFi force sleep when picoclick is charging/connected to the USB

### ISSUE THREAD

**Issue by nccchirag** [makermoekoe/Picoclick#2]
All your samples turn off WiFi when USB charging cable is connected and picoclick is charging. Shouldn't it be continuously ON with latch pin HIGH? as, it is connected to a power source. 

**Use Case:**
I have a picoclick with battery & it has drained, so, I connect it to my PC/Powerbank/Power Brick on the desk and now since it is connected to power, I would still want the button functions to be used rather than first unplugging it and then operating it.

Does the charging hardware limit this?

Please guide

**Comment by makermoekoe** [comment]
Hey, the attached files are just some basic examples. 
The idea behind this was, that I want a simple animation while the battery is charging. Nevertheless, it is possible that you can enable button press detection while the USB cable is plugged in. Therefore you have to add the `digitalRead(button)` part inside the loop. If you don't want any animation, you can delete the entire if-cause around the `status_mcp` variable and it will behave like it isn't plugged to USB.

If it will help, I can upload a new code for this.
