### ISSUE TITLE
Dead on Arrival?

### ISSUE THREAD

**Issue by suhlig** [makermoekoe/Picoclick#3]
Hi, 

my two brand new PicoClicks just arrived. They look neat, but there is no new device found
when I connect it using USB-C. Other ESPs I have appear as `/dev/cu.usbserial-1410`, but both PicoClicks I bought seem dead.

Is there something to be aware of? Any advice on how to move forward?

Regards

Steffen

**Comment by makermoekoe** [comment]
Hey Steffen,
the on board USB driver is powered by battery, so probably you have to connect a power supply between 3.5v and 6v to the battery pads behind the USB-C jack. Your PC should recognize the Picoclicks afterwards.
