### ISSUE TITLE
Silkscreen not readable

### ISSUE THREAD

**Issue by derpicknicker1** [makermoekoe/Picoclick#4]
As i wrote in a mail to @makermoekoe  I'm not able to read the silkscreen on the PCB. So it is not possible to determine which of the extension pads has which functionality.
Many thanks to @makermoekoe, who reacted instantly by adding informations about the pads to the documentaion.
Anyways, i want to post some pictures of my board, to show that it is a real issue and not me beeing blind :smile:

![PICT0002](https://user-images.githubusercontent.com/5983533/105014111-51b2a100-5a40-11eb-9b61-8b1d8f2bdb7a.jpg)
![PICT0003](https://user-images.githubusercontent.com/5983533/105014116-524b3780-5a40-11eb-9415-a0162f034f72.jpg)
![PICT0004](https://user-images.githubusercontent.com/5983533/105014118-524b3780-5a40-11eb-830e-546ef1699bd2.jpg)
![PICT0000](https://user-images.githubusercontent.com/5983533/105014119-52e3ce00-5a40-11eb-8215-102153447246.jpg)
![PICT0001](https://user-images.githubusercontent.com/5983533/105014120-52e3ce00-5a40-11eb-857f-717af94f3654.jpg)

**Comment by makermoekoe** [comment]
Overview added to the repo.
