### ISSUE TITLE
Wrong factor in getBatteryVoltage()

### ISSUE THREAD

**Issue by derpicknicker1** [makermoekoe/Picoclick#5]
In the example code for mqtt and ifttt there is a method to read the battery voltage in millivolts. But the factor in this method is wrong. It will return about 7900mV for a fully charged battery.

https://github.com/makermoekoe/Picoclick/blob/062b08edbb41c2c131e96a83faa8be95ed6d7e97/code/mqtt.cpp#L60

For the voltage divider used on the board the values are `R1 = 1MΩ` and `R2 = 250kΩ`. So the equation in the comment above should result in a factor of 5.

For me, this gives a reading of ~4200mV when the battery is fully charged, which should be correct.

**Comment by SergioEscuder** [comment]
Mine also. How did you find the voltage divider resistor values?

**Comment by derpicknicker1** [comment]
I asked @makermoekoe

**Comment by makermoekoe** [comment]
Yes, the voltage divider is `1M:250k` and therefore should be 5. 4200mV for a fully charged Lipo battery sounds great.
I have updated the values in the code.
Thanks for sharing.
