### ISSUE TITLE
Extremely low charging current

### ISSUE THREAD

**Issue by SergioEscuder** [makermoekoe/Picoclick#6]
Plugging a USB power consumption monitor reports a charging current of 0.02A (20mA).
Is this normal? What should be the correct value?
A battery will take forever to charge at this rate.
![IMG_20210121_111940](https://user-images.githubusercontent.com/2299002/105465697-89655700-5c93-11eb-889f-f7f3e89d1256.jpg)

**Comment by derpicknicker1** [comment]
Yes, it is normal. The charging current is set by a resistor connected to the cahrge controller. The resistors value is 47,5kOhm. With the equation `I = 1000V / R` the charge current is calculated. This results in `I = 1000V / 47500Ohm = 21mA`

See also [Datasheet](https://datasheet.lcsc.com/szlcsc/BLUE-ROCKET-BRCL4054BME_C328563.pdf) page 10.

The picoclick uses a 30mAh cell, so 20mA charge current is fine.

**Comment by makermoekoe** [comment]
A charging current of around 21mA is totally fine. We set the Rprog of the LiPo charger to 47,5kOhm which results (depending on the equation in the datasheet `I=1000V/R` in 21mA. 
The Picoclick is build to be used with totally small Lipo batteries of around 20-30mAh. A charging current of 20mA is something around 1C charging rate which is totally fine.

**Comment by makermoekoe** [comment]
I have added a description to the repo with the highlighted `R_prog`. Depending on the equation above you can set the charging current depending on your battery. Keep in mind that even these small batteries can be dangerous.
