### ISSUE TITLE
schematics and fusion 360 export

### ISSUE THREAD

**Issue by frankbolton** [makermoekoe/Picoclick#7]
Hi-

I saw your posts on instagram and wanted to learn from your design.
I want to make a pico size (similar battery) wearable device that works with BLE and a sensor.
Do you plan to share your electronic design (specifically the schematic) as I want to use WS2811 LEDs with a lipo battery

**Comment by derbyshire10** [comment]
@makermoekoe I would also like to alter the design to better suit different projects. Could you please publish the schematic?

**Comment by enekochan** [comment]
Yes please, even a simplified schema would be nice to learn how you achieved to include the usb charger, the ESP chip and the WiFi antena. I would love to understand how it all works. Thank you!

**Comment by derbyshire10** [comment]
@makermoekoe The new project Picoclick-C3 has the documents needed to recreate the board with your own changes.

https://github.com/makermoekoe/Picoclick-C3

**Comment by enekochan** [comment]
Thank you! Didn't knew about that repo.
