### ISSUE TITLE
BSSID to uint8_t {Solved}

### ISSUE THREAD

**Issue by RoccoWijnsma** [makermoekoe/Picoclick#8]
Hi, 

I really like the Picoclick and i'm fairly new to coding. Sorry if this is a noob question.

 The thing i struggle with is transfroming the BSSID  **e2:63:da:ae:30:67** to:
`const uint8_t bssid[6] = {0x80, 0x71, 0x7A, 0x3F, 0x8B, 0x63}; //put your access points bssid here`

Do you use a site for this convertion? 

Thank you for you're time.

**Comment by makermoekoe** [comment]
Hey, it is probably as easy as adding the `0x` before every digit. In your case this would result in
`const uint8_t bssid[6] = {0xE2, 0x63, 0xDA, 0xAE, 0x30, 0x67}; `

I you have any other questions then feel free to ask 🙂

**Comment by RoccoWijnsma** [comment]
Hahahaha I feel so stupid. Thanks for the help! Never seen a MQTT button so small! Great work.
