### ISSUE TITLE
Battery Size

### ISSUE THREAD

**Issue by neofuturism** [makermoekoe/Picoclick#9]
What would happen if I plug a 500MAH battery to the Picoclick?
will it explode :)

**Comment by makermoekoe** [comment]
Haha 😁 Of course you can do it! The only difference is that it needs longer to charge. You can change the charging current via a resistor like it is shown in the repo :)

**Comment by neofuturism** [comment]
Awesome, thank you, 
I finally found a cool project for the Pico!!

**Comment by makermoekoe** [comment]
Where do you gonna use i? :)
